-- ============================================================================
-- 0031_seed_tipos_tareas.sql · F6.3 — 16 tipos pre-configurados
--
-- Tipos críticos para una farmacia argentina (regulatorios, operativos,
-- financieros, sucursal). on conflict (codigo) do update — re-runnable.
-- ============================================================================

insert into public.tipos_tareas (
  codigo, nombre, descripcion, categoria, icono, color,
  prioridad_default, sla_horas, requiere_aprobacion, niveles_workflow,
  evidencia_requerida, rol_responsable_default, rol_verificador_default,
  es_auto_generable, permite_recurrencia, plantilla_titulo,
  puntos_completar
) values
  ('aprobar_pago', 'Aprobar pago a proveedor',
   'Revisión y aprobación de un pago a proveedor antes de la ejecución.',
   'finanzas', 'BadgeCheck', '#22c55e',
   'alta', 24, true, 2,
   '["aprobacion_digital"]'::jsonb, 'tesoreria', 'gerente',
   true, false, 'Aprobar pago a {proveedor} por {monto}',
   15),

  ('renovar_habilitacion_municipal', 'Renovar habilitación municipal',
   'Trámite anual de renovación de habilitación comercial.',
   'regulatorio', 'FileCheck', '#ef4444',
   'critica', 720, false, 2,
   '["foto","archivo"]'::jsonb, 'administrativo', 'gerente',
   true, true, 'Renovar habilitación municipal · {sucursal}',
   50),

  ('renovar_matricula_farmaceutico', 'Renovar matrícula del farmacéutico',
   'Renovación anual de matrícula profesional.',
   'regulatorio', 'IdCard', '#dc2626',
   'alta', 168, false, 1,
   '["archivo"]'::jsonb, 'administrativo', null,
   true, true, 'Renovar matrícula de {farmaceutico}',
   30),

  ('control_psicotropicos', 'Control mensual de psicotrópicos',
   'Conciliación mensual del libro de psicotrópicos contra stock.',
   'regulatorio', 'BookLock', '#7c3aed',
   'alta', 168, true, 2,
   '["firma","checklist"]'::jsonb, 'sucursal', 'gerente',
   true, true, 'Control psicotrópicos · {sucursal} · {periodo}',
   25),

  ('reponer_stock', 'Reponer stock crítico',
   'Producto por debajo del stock mínimo — solicitar reposición.',
   'operaciones', 'PackagePlus', '#f59e0b',
   'alta', 48, false, 2,
   '["foto"]'::jsonb, 'comprador', 'sucursal',
   true, false, 'Reponer {producto} en {sucursal}',
   10),

  ('gestionar_vencimiento', 'Gestionar producto próximo a vencer',
   'Producto con vencimiento próximo — decidir promoción/devolución/baja.',
   'operaciones', 'CalendarX', '#f97316',
   'media', 168, false, 1,
   '["foto"]'::jsonb, 'sucursal', null,
   true, false, 'Vencimiento próximo: {producto} · {fecha_vto}',
   15),

  ('reclamo_recepcion', 'Reclamo por diferencia en recepción',
   'Diferencia detectada en la recepción de mercadería — gestionar reclamo.',
   'compras', 'AlertTriangle', '#dc2626',
   'alta', 48, false, 2,
   '["foto","firma"]'::jsonb, 'comprador', 'gerente',
   true, false, 'Reclamo recepción {numero_remito} · {proveedor}',
   15),

  ('cierre_caja_diaria', 'Cierre de caja diaria',
   'Arqueo y cierre de la caja al final del día.',
   'sucursal', 'Wallet', '#0ea5e9',
   'alta', 12, false, 2,
   '["foto","firma","monto_arqueo"]'::jsonb, 'sucursal', 'sucursal',
   true, true, 'Cerrar caja · {sucursal} · {fecha}',
   10),

  ('apertura_sucursal', 'Apertura de sucursal',
   'Apertura matutina con check de seguridad y limpieza inicial.',
   'sucursal', 'DoorOpen', '#10b981',
   'alta', 1, false, 1,
   '["foto","gps"]'::jsonb, 'sucursal', null,
   true, true, 'Apertura · {sucursal} · {fecha}',
   5),

  ('limpieza_local', 'Limpieza del local',
   'Limpieza completa del local al inicio del día.',
   'limpieza', 'SprayCan', '#06b6d4',
   'media', 8, false, 1,
   '["foto","checklist"]'::jsonb, 'sucursal', null,
   true, true, 'Limpieza local · {sucursal}',
   5),

  ('limpieza_banos', 'Limpieza de baños',
   'Limpieza de baños — 3 veces por día.',
   'limpieza', 'Droplets', '#0891b2',
   'media', 4, false, 1,
   '["foto","firma"]'::jsonb, 'sucursal', null,
   true, true, 'Limpieza baños · {sucursal} · {turno}',
   3),

  ('control_cadena_frio', 'Control cadena de frío',
   'Verificación diaria de heladera con foto del termómetro.',
   'regulatorio', 'Thermometer', '#0ea5e9',
   'critica', 8, false, 1,
   '["foto_termometro","checklist"]'::jsonb, 'sucursal', null,
   true, true, 'Cadena de frío · {sucursal} · {fecha}',
   8),

  ('conciliacion_bancaria', 'Conciliación bancaria semanal',
   'Conciliación de extractos bancarios del período.',
   'finanzas', 'GitMerge', '#14b8a6',
   'alta', 168, false, 2,
   '["archivo"]'::jsonb, 'tesoreria', 'gerente',
   true, true, 'Conciliación · {cuenta} · {periodo}',
   20),

  ('carga_factura_proveedor', 'Cargar factura de proveedor',
   'Ingresar factura nueva al sistema con su PDF/imagen.',
   'compras', 'FilePlus', '#3b82f6',
   'media', 72, false, 1,
   '["archivo"]'::jsonb, 'administrativo', null,
   true, false, 'Cargar factura {numero} · {proveedor}',
   10),

  ('llamado_cliente_vip', 'Llamado a cliente VIP',
   'Contactar a cliente VIP en seguimiento comercial.',
   'comercial', 'PhoneCall', '#8b5cf6',
   'media', 168, false, 1,
   '["nota","duracion"]'::jsonb, 'administrativo', null,
   true, false, 'Llamar a {cliente}',
   15),

  ('otro', 'Tarea genérica',
   'Tarea sin tipo predefinido — usar para casos puntuales.',
   'otro', 'ListTodo', '#94a3b8',
   'media', null, false, 1,
   '[]'::jsonb, null, null,
   false, false, '{titulo}',
   5)
on conflict (codigo) do update set
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  categoria = excluded.categoria,
  icono = excluded.icono,
  color = excluded.color,
  prioridad_default = excluded.prioridad_default,
  sla_horas = excluded.sla_horas,
  requiere_aprobacion = excluded.requiere_aprobacion,
  niveles_workflow = excluded.niveles_workflow,
  evidencia_requerida = excluded.evidencia_requerida,
  rol_responsable_default = excluded.rol_responsable_default,
  rol_verificador_default = excluded.rol_verificador_default,
  es_auto_generable = excluded.es_auto_generable,
  permite_recurrencia = excluded.permite_recurrencia,
  plantilla_titulo = excluded.plantilla_titulo,
  puntos_completar = excluded.puntos_completar,
  updated_at = now();
