-- 0038 · Seed de 16 tipos de tareas de farmacia (F6-T · T3)
-- Idempotente: on conflict (codigo) do update. Usa columnas de 0037
-- (alcance, verificacion_humana, checklist_items).

insert into public.tipos_tareas
  (codigo, nombre, descripcion, categoria, icono, color, prioridad_default, sla_horas,
   verificacion_humana, verificacion_ia, ia_prompt_verificacion,
   evidencia_requerida, checklist_items, puntos_completar, alcance,
   permite_recurrencia, es_auto_generable, activo)
values
  ('apertura_sucursal','Apertura de sucursal','Apertura diaria del local','sucursal','DoorOpen','#6E3CDB','media',1,
    true,true,'Verificá que la foto muestre el frente del local abierto con luces encendidas o persiana levantada',
    '["foto","gps"]'::jsonb,null,5,'global',true,true,true),
  ('cierre_sucursal','Cierre de sucursal','Cierre diario del local','sucursal','DoorOpen','#6E3CDB','media',null,
    true,true,null,'["foto"]'::jsonb,null,5,'global',true,true,true),
  ('cierre_caja_diaria','Cierre de caja diaria','Arqueo y cierre de caja','sucursal','Wallet','#10b981','critica',null,
    true,true,null,'["monto_arqueo","firma"]'::jsonb,null,10,'global',true,true,true),
  ('control_cadena_frio','Control de cadena de frío','Lectura de temperatura de heladera','cadena_frio','Thermometer','#0ea5e9','alta',null,
    true,true,'Leé la temperatura del termómetro en la foto. Aprobada si está entre 2 y 8 grados. Indicá la temperatura leída.',
    '["foto_termometro"]'::jsonb,null,8,'global',true,true,true),
  ('limpieza_local','Limpieza del local','Limpieza general del local','limpieza','SprayCan','#22c55e','media',null,
    false,true,'Verificá que el local se vea limpio y ordenado: piso sin residuos, góndolas prolijas',
    '["foto","checklist"]'::jsonb,'["Piso limpio","Góndolas ordenadas","Mostrador despejado","Vidrios limpios"]'::jsonb,5,'global',true,true,true),
  ('limpieza_banos','Limpieza de baños','Limpieza de baños','limpieza','Droplets','#22c55e','media',null,
    true,true,'Verificá que el baño se vea limpio: piso, lavabo y espejo sin manchas visibles',
    '["foto"]'::jsonb,null,3,'global',true,true,true),
  ('control_psicotropicos','Control de psicotrópicos','Conteo y control regulatorio mensual','regulatorio','BookLock','#ef4444','critica',null,
    true,true,null,'["checklist","firma"]'::jsonb,
    '["Conteo físico coincide con registro","Libro recetario al día","Recetas archivadas","Faltantes reportados"]'::jsonb,25,'global',true,true,true),
  ('reposicion_gondolas','Reposición de góndolas','Reposición semanal de góndolas','operaciones','PackagePlus','#f59e0b','media',null,
    false,true,null,'["foto"]'::jsonb,null,8,'global',true,true,true),
  ('control_vencimientos_gondola','Control de vencimientos','Revisión de vencimientos en góndola','operaciones','CalendarClock','#f59e0b','alta',null,
    true,true,null,'["checklist"]'::jsonb,
    '["Productos <90 días identificados","Rotación FIFO aplicada","Vencidos retirados"]'::jsonb,10,'global',true,true,true),
  ('recepcion_mercaderia','Recepción de mercadería','Recepción y control de mercadería','compras','PackageCheck','#3b82f6','alta',null,
    true,true,null,'["foto","checklist"]'::jsonb,
    '["Bultos coinciden con remito","Sin daños visibles","Cadena de frío respetada si aplica"]'::jsonb,10,'global',true,false,true),
  ('conciliacion_caja_semanal','Conciliación de caja semanal','Conciliación semanal de caja','finanzas','Scale','#10b981','alta',null,
    true,true,null,'["nota"]'::jsonb,null,20,'global',true,true,true),
  ('deposito_efectivo','Depósito de efectivo','Depósito bancario de efectivo','finanzas','Banknote','#10b981','alta',null,
    true,true,null,'["foto","monto_arqueo"]'::jsonb,null,10,'global',true,false,true),
  ('mantenimiento_equipo','Mantenimiento de equipo','Mantenimiento de equipamiento','sucursal','Wrench','#6E3CDB','media',null,
    true,true,null,'["foto","nota"]'::jsonb,null,8,'global',true,false,true),
  ('capacitacion_pendiente','Capacitación pendiente','Capacitación de personal','rrhh','GraduationCap','#f43f5e','media',null,
    true,true,null,'["nota"]'::jsonb,null,15,'global',true,false,true),
  ('llamado_cliente_vip','Llamado a cliente VIP','Contacto comercial con cliente VIP','comercial','PhoneCall','#ec4899','media',null,
    true,true,null,'["nota"]'::jsonb,null,15,'global',true,false,true),
  ('tarea_libre','Tarea libre','Tarea genérica con evidencia configurable','otro','ListTodo','#6b7280','media',null,
    true,true,null,'[]'::jsonb,null,5,'global',true,false,true)
on conflict (codigo) do update set
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  categoria = excluded.categoria,
  icono = excluded.icono,
  color = excluded.color,
  prioridad_default = excluded.prioridad_default,
  sla_horas = excluded.sla_horas,
  verificacion_humana = excluded.verificacion_humana,
  verificacion_ia = excluded.verificacion_ia,
  ia_prompt_verificacion = excluded.ia_prompt_verificacion,
  evidencia_requerida = excluded.evidencia_requerida,
  checklist_items = excluded.checklist_items,
  puntos_completar = excluded.puntos_completar,
  alcance = excluded.alcance,
  updated_at = now();
