-- 0055 · Módulo Ofertas (v0.22). (Resumen; SQL real aplicado vía MCP.)
-- Enums: campania_origen, campania_estado, oferta_tipo, oferta_vigencia,
-- oferta_estado, oferta_propuesta_por. Tablas: campanias, ofertas (objeto vivo
-- con codigo OF-YYYY-NNNN, version, limites, b2b, metricas, cuponera_ref),
-- ofertas_confirmaciones, ofertas_versiones, ofertas_aprendizaje, ofertas_experimentos.
-- RLS: gestión super/gerente/administrativo; confirmaciones las escribe cada empleado.
